// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestArtur.Data;
using TestArtur.Models;

namespace TestArtur.Migrations
{
    [DbContext(typeof(NovostiContext))]
    [Migration("20220111140732_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TestArtur.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naimenovanie")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorys");
                });

            modelBuilder.Entity("TestArtur.Models.Novost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datadobavleniya")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kartinka")
                        .HasColumnType("TEXT");

                    b.Property<int>("TegId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Vidimost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Zagolovok")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TegId");

                    b.ToTable("Novosts");
                });

            modelBuilder.Entity("TestArtur.Models.Teg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazvanie")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tegs");
                });

            modelBuilder.Entity("TestArtur.Models.Novost", b =>
                {
                    b.HasOne("TestArtur.Models.Teg", "Teg")
                        .WithMany("Novosts")
                        .HasForeignKey("TegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teg");
                });

            modelBuilder.Entity("TestArtur.Models.Teg", b =>
                {
                    b.HasOne("TestArtur.Models.Category", "Category")
                        .WithMany("Tegs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TestArtur.Models.Category", b =>
                {
                    b.Navigation("Tegs");
                });

            modelBuilder.Entity("TestArtur.Models.Teg", b =>
                {
                    b.Navigation("Novosts");
                });
#pragma warning restore 612, 618
        }
    }
}
